application: indaxone-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /ux/main
  static_files: static/ux/index.html
  upload: static/ux/index.html
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
